name: NodeJS
on: 
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.7
      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test